# Generated by Django 2.2.7 on 2019-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(blank=True, default='')),
                ('result', models.TextField(blank=True, default='')),
                ('is_good_result', models.BooleanField(default=False)),
            ],
        ),
    ]
